# Global configurations applied to all models unless overridden
# Note: when using pi.dev the context size set in the models.json takes precedence over the ctx-size set in this file
[*]
ctx-size = 32768

# 32K Context Window (~68 tokens per second)
[Qwen3.6-35B-A3B-UD-IQ4_XS-32k]
alias          = qwen36-35b-32k
model          = /home/onyx/.cache/llama.cpp/Qwen3.6-35B-A3B-UD-IQ4_XS.gguf
mmproj         = /home/onyx/.cache/llama.cpp/Qwen3.6-35B-mmproj-F16.gguf
n-gpu-layers   = 99
split-mode     = row
tensor-split   = 1,1
flash-attn     = true
cache-type-k   = q8_0
cache-type-v   = q8_0
ctx-size       = 32768
batch-size     = 2048
ubatch-size    = 1024
parallel       = 1
cont-batching  = true
jinja          = true
temp           = 1.0
top-k          = 20
top-p          = 0.95
min-p          = 0.0
repeat-penalty = 1.0

# 64K (Balanced) Context Window (~40 tokens per second)
[Qwen3.6-35B-A3B-UD-IQ4_XS-64k-balanced]
alias          = qwen36-35b-64k-balanced
model          = /home/onyx/.cache/llama.cpp/Qwen3.6-35B-A3B-UD-IQ4_XS.gguf
mmproj         = /home/onyx/.cache/llama.cpp/Qwen3.6-35B-mmproj-F16.gguf
n-gpu-layers   = 99
split-mode     = row
tensor-split   = 1,1
flash-attn     = true
cache-type-k   = q4_0
cache-type-v   = q4_0
ctx-size       = 65536
batch-size     = 1536
ubatch-size    = 768
parallel       = 1
cont-batching  = true
jinja          = true
temp           = 1.0
top-k          = 20
top-p          = 0.95
min-p          = 0.0
repeat-penalty = 1.0

# 64K (Safe) Context Window (~30 tokens per second)
[Qwen3.6-35B-A3B-UD-IQ4_XS-64k-safe]
alias          = qwen36-35b-64k-safe
model          = /home/onyx/.cache/llama.cpp/Qwen3.6-35B-A3B-UD-IQ4_XS.gguf
mmproj         = /home/onyx/.cache/llama.cpp/Qwen3.6-35B-mmproj-F16.gguf
n-gpu-layers   = 99
split-mode     = row
tensor-split   = 1,1
flash-attn     = true
cache-type-k   = q4_0
cache-type-v   = q4_0
ctx-size       = 65536
batch-size     = 1024
ubatch-size    = 512
parallel       = 1
cont-batching  = true
jinja          = true
temp           = 1.0
top-k          = 20
top-p          = 0.95
min-p          = 0.0
repeat-penalty = 1.0

# 96K (Stretch) Context Window (~30 tokens per second)
[Qwen3.6-35B-A3B-UD-IQ4_XS-96k-stretch]
alias          = qwen36-35b-96k-stretch
model          = /home/onyx/.cache/llama.cpp/Qwen3.6-35B-A3B-UD-IQ4_XS.gguf
mmproj         = /home/onyx/.cache/llama.cpp/Qwen3.6-35B-mmproj-F16.gguf
n-gpu-layers   = 99
split-mode     = row
tensor-split   = 1,1
flash-attn     = true
cache-type-k   = q4_0
cache-type-v   = q4_0
ctx-size       = 98304
batch-size     = 1024
ubatch-size    = 512
parallel       = 1
cont-batching  = true
jinja          = true
temp           = 1.0
top-k          = 20
top-p          = 0.95
min-p          = 0.0
repeat-penalty = 1.0

# 128K (Stretch) Context Window (~30 tokens per second)
[Qwen3.6-35B-A3B-UD-IQ4_XS-128k-stretch]
alias          = qwen36-35b-128k-stretch
model          = /home/onyx/.cache/llama.cpp/Qwen3.6-35B-A3B-UD-IQ4_XS.gguf
mmproj         = /home/onyx/.cache/llama.cpp/Qwen3.6-35B-mmproj-F16.gguf
n-gpu-layers   = 99
split-mode     = row
tensor-split   = 1,1
flash-attn     = true
cache-type-k   = q4_0
cache-type-v   = q4_0
ctx-size       = 131072
batch-size     = 1024
ubatch-size    = 512
parallel       = 1
cont-batching  = true
jinja          = true
temp           = 1.0
top-k          = 20
top-p          = 0.95
min-p          = 0.0
repeat-penalty = 1.0

[qwen3-coder:30b]
alias = qwen3-coder-30b
model = /usr/share/ollama/.ollama/models/blobs/sha256-1194192cf2a187eb02722edcc3f77b11d21f537048ce04b67ccf8ba78863006a
#ctx-size = 262144

[qwen3.5:9b]
alias = qwen35-9b
model = /usr/share/ollama/.ollama/models/blobs/sha256-dec52a44569a2a25341c4e4d3fee25846eed4f6f0b936278e3a3c900bb99d37c
#ctx-size = 131072

[gpt-oss:20b]
alias = gpt-oss-20b
model = /usr/share/ollama/.ollama/models/blobs/sha256-b112e727c6f18875636c56a779790a590d705aec9e1c0eb5a97d51fc2a778583
#ctx-size = 131072

[gemma4:12b]
alias = gemma4-12b
model = /usr/share/ollama/.ollama/models/blobs/sha256-1278394b693672ac2799eadc9a83fd98259a6a88a40acfb1dcaa6c6fc895a606
mmproj = /usr/share/ollama/.ollama/models/blobs/sha256-675ad6e68101ca9413ec806855c452362f0213f2dfc5800996b086fdb8119842
#ctx-size = 262144

[north-mini-code-1.0:q4_K_M]
alias = north-mini-code-1.0-q4_k_m
model = /usr/share/ollama/.ollama/models/blobs/sha256-2e6b0d32b7ff9d61f77d6808307db4791f487a72b22da0b28f5d4293b5729282
#ctx-size = 500000

[gemma-4-12b-it-UD-Q4_K_XL]
alias          = gemma4-12b-q4_k_xl
model          = /home/onyx/.cache/llama.cpp/gemma-4-12b-it-UD-Q4_K_XL.gguf
mmproj         = /home/onyx/.cache/llama.cpp/gemma4-12B-mmproj-F16.gguf
n-gpu-layers   = 99
flash-attn     = true
cache-type-k   = q8_0
cache-type-v   = q8_0
ctx-size       = 131072
batch-size     = 4096
ubatch-size    = 4096
parallel       = 1
cont-batching  = true
jinja          = true
temp           = 1.0
top-p          = 0.95
top-k          = 64
