# Global configurations applied to all models unless overridden
# Note: when using pi.dev the context size set in the models.json takes precedence over the ctx-size set in this file
[*]
ctx-size = 32768

[Qwen3.6-35B-A3B-UD-IQ4_XS]
model          = ~/.cache/llama.cpp/Qwen3.6-35B-A3B-UD-IQ4_XS.gguf
mmproj         = ~/.cache/llama.cpp/Qwen3.6-35B-mmproj-F16.gguf
n-gpu-layers   = 99
split-mode     = row
tensor-split   = 1,1
flash-attn     = true
cache-type-k   = q8_0
cache-type-v   = q8_0
ctx-size       = 32768
batch-size     = 4096
ubatch-size    = 4096
parallel       = 1
cont-batching  = true
jinja          = true
temp           = 1.0
top-k          = 20
top-p          = 0.95
min-p          = 0.0
repeat-penalty = 1.0

[qwen3-coder:30b]
model = /usr/share/ollama/.ollama/models/blobs/sha256-1194192cf2a187eb02722edcc3f77b11d21f537048ce04b67ccf8ba78863006a
#ctx-size = 262144

[north-mini-code-1.0:q4_K_M]
model = /usr/share/ollama/.ollama/models/blobs/sha256-2e6b0d32b7ff9d61f77d6808307db4791f487a72b22da0b28f5d4293b5729282
#ctx-size = 500000

[gemma-4-12b-it-UD-Q4_K_XL]
model          = ~/.cache/llama.cpp/gemma-4-12b-it-UD-Q4_K_XL.gguf
mmproj         = ~/.cache/llama.cpp/gemma4-12B-mmproj-F16.gguf
n-gpu-layers   = 99
flash-attn     = true
cache-type-k   = q8_0
cache-type-v   = q8_0
ctx-size       = 131072
batch-size     = 4096
ubatch-size    = 4096
parallel       = 1
cont-batching  = true
jinja          = true
temp           = 1.0
top-p          = 0.95
top-k          = 64
